name: FTP Auto Deploy

on:
  push:
    branches: [ main-cn ]  # 当代码推送到 main 分支时触发

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync via LFTP
      run: |
        sudo apt-get install lftp
        lftp -e "
        set ftp:passive-mode off; 
        set ftp:ssl-allow no;
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
        mirror -R ./ ./httpdocs --reverse --delete --verbose --exclude .git/ --exclude .github/ --exclude Templates/;
        quit
        "